### PR TITLE
[WIP] Add English language for GUI

### PR DESCRIPTION
**Pull request by RedDeadDepresso**
Hi, I tried to translate the GUI and this is the result.

Please note that translations may not be accurate as I don't know Chinese and some sentences have been shortened as they would otherwise break the GUI layout.

Also, I only play on the Global server, so I haven't been able to test it on other servers.

Feel free to edit the translations. You can find the guide [here](https://github.com/RedDeadDepresso/blue_archive_auto_script/blob/master/gui/README.md).

### CODE REVIEW

**Comment by Kiramei** [comment]
Tahnks, your work is definitely AWESOME! However, here I wonder how your work can be compatible with the dynamic-changing config which goes with `static.json`. For example, the name of  shop goods cannot be translated as it comes from the json.

**Comment by Kiramei** [comment]
If it can be solved, we will translate the app  in Japanese as well.

**Comment by Kiramei** [comment]
Bro, your work goes conflicted with Pur1fying's work this afternoon : )
But anyway, thanks, just go ahead.

**Comment by pur1fying** [comment]
@RedDeadDepresso Thank you for your contribution，but ui author @Kiramei  and I are occpied for the study and competitions these days，so it will take a few days（1-2weeks）to review your code.By the way，I am translating the descriptions_en_US this afternoon.It‘s a pity that our work conflicts. Have a good day!

**Comment by RedDeadDepresso** [comment]
> Tahnks, your work is definitely AWESOME! However, here I wonder how your work can be compatible with the dynamic-changing config which goes with `static.json`. For example, the name of shop goods cannot be translated as it comes from the json.

I was able to translate the name of the goods using the same method I described in the guide: add anything that will be displayed in the GUI from the config files in ConfigTranslation's dictionary and access it using bt.tr('ConfigTranslation', goods_name). 

Also I noticed there is a small mistake in the tactical_challenge_shop_price_list
```python
    "tactical_challenge_shop_price_list": {
...
        "Global": [
             ["静子神明文字x5",50],["真白神明文字x5",50],["纱绫神明文字x5",50],["风香神明文字x5",50],
             ["歌原神明文字x5",50],["30AP", 15],["60AP", 30], ["初级经验书x5", 5],
             ["中级经验书x10", 25],["高级经验书x3", 60],["特级经验书x1", 100],["信用点x5k", 4],
             ["信用点x5k", 20],["信用点x75k", 60],["信用点x125k", 10]
        ],
``` 
Screenshot_20240409-191218
wouldn't ["中级经验书x10", 25] be before ["初级经验书x5", 5]?

**Comment by RedDeadDepresso** [comment]
> @RedDeadDepresso Thank you for your contribution，but ui author @Kiramei and I are occpied for the study and competitions these days，so it will take a few days（1-2weeks）to review your code.By the way，I am translating the descriptions_en_US this afternoon.It‘s a pity that our work conflicts. Have a good day!

It's fine, no need to rush. Also, I'm sorry that I caused conflict with your work.

**Comment by Kiramei** [comment]
Since the final test has finished, it's time to set the PR onto the schedule. @pur1fying

**Comment by Kiramei** [comment]
Hi! How are you going on?We'll settle down on merging your branch into our `master` branch in these days. And sorry for taking too much time on this branch as we intend to translate this to Japanese version, as well. Thanks for your contribution.

**Comment by RedDeadDepresso** [comment]
> Hi! How are you going on?We'll settle down on merging your branch into our `master` branch in these days. And sorry for taking too much time on this branch as we intend to translate this to Japanese version, as well. Thanks for your contribution.

Hi, I was really busy and I'm sorry I couldn't work on the script. I'll make another pull request on the test branch tomorrow since the translations aren't finished yet.

**Pull request closed without merging**
