### PR TITLE
English translation for the GUI

### PR DESCRIPTION
**Pull request by RedDeadDepresso**
Hi, I managed to translate most of the GUI, although some translations might not be accurate. You can open en_US.ts on qtLinguist and see which translations I'm unsure, they have a question mark or an exclamation mark.

I also added the Japanese option in the GUI and tried to translate using a python library called [translators](https://github.com/UlionTse/translators). You can find the code in auto_translate.py and try different translators. Hope it helps.

### CODE REVIEW

**Comment by Kiramei** [comment]
@pur1fying Now that the Japanese version has been finished, please check and if there's no problem, merge the branch into the `master` branch.

**Comment by VoltIcaRus** [comment]
@RedDeadDepresso 


I'm trying to use the procedure to use auto_translate.py. I'm trying to use the papago handler
After installing  required by requirements-i18n.txt
```
if __name__ == "__main__":
    pylupdate = Pylupdate5Handler()
    gui = XmlHandler()
    descriptions = HtmlHandler()
    lrelease = LreleaseHandler()
    model = ModelHandler()
    ts = XmlHandler()

    request_ko = Request([pylupdate, gui, lrelease], Language.KOREAN, 'Papago', 'zh-Hans', 'ko')
    request_ko.process()

    request_jp = Request([gui], Language.JAPANESE, 'bing', 'zh-Hans', 'ja')
    request_jp.process()
    
  ```
 ```
 if __name__ == "__main__":
    pylupdate = Pylupdate5Handler()
    gui = XmlHandler()
    descriptions = HtmlHandler()
    lrelease = LreleaseHandler()

  

    model = Pylupdate5Handler()
    ts = XmlHandler()
    descriptions = HtmlHandler()

    request_ko = Request([model, ts, descriptions], Language.KOREAN, 'ko')
    request_ko.process()

```
I tried a few things
In the last line
I added this but it just print python and didn't run so I don't know where it went wrong. Am I misinterpreting the explanation?
...
Okay I've tried several times 
only python text is output and I don't know what to do. help me...

**Comment by RedDeadDepresso** [comment]
> @RedDeadDepresso
> 
> I'm trying to use the procedure to use auto_translate.py. I'm trying to use the papago handler After installing required by requirements-i18n.txt
> 
> ```
> if __name__ == "__main__":
>     pylupdate = Pylupdate5Handler()
>     gui = XmlHandler()
>     descriptions = HtmlHandler()
>     lrelease = LreleaseHandler()
>     model = ModelHandler()
>     ts = XmlHandler()
> 
>     request_ko = Request([pylupdate, gui, lrelease], Language.KOREAN, 'Papago', 'zh-Hans', 'ko')
>     request_ko.process()
> 
>     request_jp = Request([gui], Language.JAPANESE, 'bing', 'zh-Hans', 'ja')
>     request_jp.process()
>     
> ```
> 
> ```
> if __name__ == "__main__":
>    pylupdate = Pylupdate5Handler()
>    gui = XmlHandler()
>    descriptions = HtmlHandler()
>    lrelease = LreleaseHandler()
> 
>  
> 
>    model = Pylupdate5Handler()
>    ts = XmlHandler()
>    descriptions = HtmlHandler()
> 
>    request_ko = Request([model, ts, descriptions], Language.KOREAN, 'ko')
>    request_ko.process()
> ```
> 
> I tried a few things In the last line I added this but it just print python and didn't run so I don't know where it went wrong. Am I misinterpreting the explanation? ... Okay I've tried several times only python text is output and I don't know what to do. help me...😂

'Papagao' should be all in lowercase. You can find the list of translators using 
```
print(ts.translators_pool)
```
so the lines would be:
```
    request_ko = Request([pylupdate, gui, lrelease], Language.KOREAN, 'papago', 'zh-Hans', 'ko')
    request_ko.process() 
```
Just make sure to add  gui/i18n/ko_KO.ts \ at the end of i18n.pro before running auto_translate.py. I can help you more if you commit changes to the fork.

**Comment by RedDeadDepresso** [comment]
@VoltIcaRus I made a pull request to your fork.

**Pull request merged**
